circus-tent/circus

CONTRIBUTORS.txt
circus/arbiter.py
circus/tests/test_arbiter.py

This 'cb' argument corresponds to a callback which will be called after the watchers have been started, if no loop has been provided.
It is called 'cb' and not 'callback' as otherwise it would conflict with the 'callback' argument accepted by every coroutines. Note that we can't use this argument here as arbiter.start will not return until the end, so the callback would never be called.
This is really helpful for projects using Circus as a library and not wanting to use a custom loop, as it allows them to call a coroutine inside the loop after everything has been initialized.
Providing a custom loop for Circus can be very hard, as you have to rewrite a lot of code to handle the shutdown properly. For example you have to write your own sighandlers. With this argument, most projects don't …

Add start callback

---

circus/controller.py

Sometimes (I don't remember the exact conditions though) `stream.send` can raise an `IOError`. We need to catch it.

Controller: Catch IOError in send_response

---

circus/tests/test_pidfile.py

From Popen's documentation.
> The shell argument (which defaults to False) specifies whether to use the shell as the program to execute. If shell is True, it is recommended to pass args as a string rather than as a sequence.
This caused the python shell to be spawned during the tests.

Fix #804, don't pass argv sequence to Popen with shell=True.

---

circus/util.py

Fixed according to discussion on #875 .
Works on Linux (Ubuntu 14.04) , SunOS(Solaris, illumos derivatives like SmartOS, OmniOS) and FreeBSD 10.

SunOS Multicast fix

---

circus/commands/sendsignal.py
circus/process.py
circus/tests/test_command_signal.py
circus/watcher.py

This addresses #880. When the parameter `recursive` is True, the signal is send to all descendants of the process and not just to its children.

Send signal with 'recursive=True' really recursive

---

circus/watcher.py

As it stands right now, when circus is restarted, having the same variance leads all the processes of a service to be killed simultaneously. By calculating the variance for each one, we can spread the recycling.

Recalculate max_age for each process

---

circus/watcher.py

Hello,
i was writting plugin which needed to check whether watcher has set `respawn` option. I couldn't do it because `respawn` option was missing in `watcher.optnames` and `get` command validates `keys` according to list of `optnames`.
Here I send simple PR which allows to get `respawn` option value using `get` command from plugin API.
Please consider merging this PR as other users may have same problem.
Thank you!

respawn option name added to optnames.

---

circus/tests/test_papa_stream.py
circus/watcher.py

This change will close the redirected streams on watcher.stop() and if the after_start hook indicates that we should abort startup. Should address issue reported by @bengecko in #884.

Close the output streams if all watcher processes are stopping

---

docs/source/for-devs/writing-hooks.rst

In `hooks.rst`, the `priority` settings are inverted in the examples (as written, the examples suggest that *lower* numbers are started first). This PR fixes the examples.
[`configuration.rst`](https://github.com/circus-tent/circus/blob/92aa3c6214e2730a7f67043268a636a5a233a4ce/docs/source/for-ops/configuration.rst) states (*emphasis* added):
> ***priority*** [¶] Integer that defines a priority for the watcher. When the Arbiter do some operations on all watchers, it will sort them with this field, *from the bigger number to the smallest*. Defaults to 0.
But [`hooks.rst`](https://github.com/circus-tent/circus/blob/92aa3c6214e2730a7f67043268a636a5a233a4ce/docs/source/for-devs/writing-hooks.rst) states:
>  With Circus you can order the startup by using the `priority` option: [¶] `...` [¶] …

READY FOR REVIEW - Fix inconsistency between configuration and hooks docs regarding priority setting

---

circus/util.py

The call to "get_cmdline", from "circus.util.get_info", was raising an
AccesDenied exception on the watcher process.

Fix for "circus.util.get_info"

---

circus/commands/restart.py

Always match lower case watcher name when stop/start/restart a watcher.
Option 1 suggested by @k4n4r in issue circus-tent/circus#927

Match lower case when start/stop/restart a watcher

---

circus/plugins/statsd.py

Fix TypeError sending message to statsd socked

---

circus/papa_process_proxy.py

The Papa code was relying on the stream to read the exit status and clear the old process. If there is no redirect, we need to do a preemptive check and simply remove the old process since the output is never pumped.

Handle case where use_papa but no redirect

---

circus/commands/decrproc.py
circus/tests/test_command_decrproc.py
circus/tests/test_command_incrproc.py
circus/tests/test_command_quit.py

Issue #686 was partially fixed by disabling the decr link in circus-web but the problematic behaviour is still accessible through `circusctl decr` and presumably raw ZMQ.
This replaces PR #931.
Just like 931 it:
- Renames `DecrProcess` to `DecrProc` for consistency with `IncrProc`
- Implements the same singleton checking logic as `IncrProc` in `DecrProc`
- Adds tests for the correct behaviour in both commands given singleton watchers
Contrary to 931, to address @douardda's comment on 931, it:
- Spreads the changes across 4 commits instead of 2
- Uses a subclass of `FakeArbiter` to support singleton `FakeWatcher`s, instead of refactoring `FakeArbiter` to support dependency injection of the watcher class.  This is similar to how `test_command_set.py` subclasses `FakeArbiter` and does not …

Fix issue #686 for circusctl as well (refactored)

---

circus/commands/__init__.py
circus/commands/kill.py
circus/plugins/watchdog.py
circus/tests/test_command_kill.py
circus/util.py
circus/watcher.py

Continuation of #938 
This sets `graceful_timeout` and `signum` as options instead of positional arguments, and fixes the tests for Python 3.

[Continuation of #938] New 'kill' command used by Watchdog to gracefully stop the processes

---

circus/sockets.py
circus/tests/test_sockets.py
docs/source/for-ops/configuration.rst

The configuration for sockets support many options, but doesn't support specifying a socket as blocking or non-blocking. Suggest to add support for this as a new boolean field `blocking`.
". For example:
```
[socket:test]
host = 0.0.0.0
port = 8000
blocking = true
```
This creates a blocking socket on port 8000. If the parameter is absent, it will assume the value of "false", in keeping with the current default behaviour.

Cannot specify socket as blocking

---

docs/source/tutorial/rationale.rst

- `autostart=true` can be removed because [it is the default](https://github.com/Supervisor/supervisor/blob/3.3.0/supervisor/skel/sample.conf#L66).
- `autorestart=true` can also be removed.  The default value of [`autorestart=unexpected`](https://github.com/Supervisor/supervisor/blob/3.3.0/supervisor/skel/sample.conf#L69) is better because the Circus page says the process should be "restarted in case it crashes".  `autorestart=true` would restart unconditionally, including if the process exited with status 0 (success).  The default value of `autorestart=unexpected` will restart the process if it crashes.

Shorten supervisord.conf example by using the defaults

---

README.rst
docs/source/man/circus-top.rst
docs/source/man/circusctl.rst
docs/source/man/circusd-stats.rst
docs/source/man/circusd.rst
docs/source/tutorial/rationale.rst
docs/source/tutorial/step-by-step.rst
docs/source/usecases.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

docs/source/tutorial/rationale.rst

This corrects a mistake that says Supervisor does not have a socket manager.  An [example of using Supervisor's socket manager](https://chaussette.readthedocs.io/en/1.3.0/#using-chaussette-in-supervisor) can be found in the Chaussette documentation.

Mention Supervisor socket manager and link to Chaussette

---

circus/config.py
circus/tests/config/empty_section.ini
circus/tests/test_config.py

Circus startup might otherwise crash, if configuration is modified by an automated script which does not remove empty sections – which can happen if configured by the [puppet-circus](https://github.com/daenney/puppet-circus) module, which uses [puppetlabs-inifile](https://github.com/puppetlabs/puppetlabs-inifile).

Guard against accidental empty ini sections

---

circus/watcher.py

Coerce `max_retry` value to int so spawn_process() doesn't choke on a INI-sourced override for this value (which arrives as a str). Otherwise, when using the flapping plugin and setting `max_retry` from `circus.ini`, one will get an "unorderable types" exception.

Coerce 'max_retry' value to int

---

circus/tests/support.py
circus/tests/test_arbiter.py
circus/watcher.py

Hey @k4nar , I fixed these two tests by looking at what the other tests were doing. A few things:
* `start_arbiter` is the favored method of creating&starting an arbiter. These two tests were the last things that used `._run_circus`, so I canned it.  `_test_udp_discovery` (a disabled test) still references ._run_circus, but if it's fixed it should use start_arbiter too.
* Had to use `AsyncCircusClient` so simultaneously send a message and poll for the result.
Code review is appreciated :)
And just FYI, I am fixing these tests in preparation for a "find relative plugin" PR.

Fix and enable two plugin tests

---

circus/arbiter.py
circus/watcher.py

`Watcher.reap_process()` uses `os.waitpid()` with `WNOHANG` flag to get child process status. It had an `OSError` exception handler checking if `errno` equals `EAGAIN`, in which case it would sleep a bit and call `waitpid` again. This mechanism was probably added to handle a case when child process has not died yet, so `waitpid` would block if not for `WNOHANG`.
However, in case a child with such a `pid` is still alive, `os.waitpid()` won't throw an exception, instead it will return a tuple `(0, 0)`, as stated [in the docs](https://docs.python.org/2/library/os.html#os.WNOHANG) (underlying function `waitpid` from `libc` does the same, returning `0` in this case).
As a result, reap_process() failed to correctly check if a child was still alive, causing it to
* before commit …

Wait for a child to finish in Watcher.reap_process

---

circus/plugins/__init__.py

This should fix stalled builds and prevent unnecessary occasional worker restarts - see #1038.
Circus can compare string reprs of config to detect a change (for example, it compares commands and stringified config is a part of a command to launch plugin). Converting to string is done by iterating over the dict, which depends on the order of items in it, which can be different for equal dicts. Sorting items of dict before putting them to string will guarantee equal config strings for equal configs.

Fix #1038 - sort string representation of plugin config

---

CONTRIBUTORS.txt
circus/arbiter.py

Missing yield on `watcher.set_numprocesses` call was causing
this coroutine to run and spawn processes while @synchronized lock
was already released. So this coroutine could overlap with the next
pump of `manage_watchers` and cause a lot more processes to be
spawned than necessary.

Fix #997 - reloadconfig concurrency

---

circus/controller.py

The `SysHandler` class issues `quit` command when it catches the
`SIGTERM` signal. This command in its turn calls `arbiter.stop()`,
but if you put a breakpoint into this function you will notice
that it's beign called twice, once from `quit` command and once
from this weird place in controller's command dispatch callback.
I digged through history and it looks like leftovers of some old
command refactoring.

Fix #998 - premature shutdown leaking processes

---

circus/circusctl.py
circus/controller.py
circus/tests/test_circusctl.py

Making circusctl return non-zero exit code when command resulted
in `staus == "error"`.

Fixing #1001 - non-zero exit code on conflict errors

---

circus/tests/support.py
circus/tests/test_client.py
circus/tests/test_watcher.py

In Python 3.7.0, 'async' is now a reserved keyword of the language, so
it cannot be used as an method argument name. When used, it causes the
following byte-compilation failure:
Traceback (most recent call last):
File "/home/thomas/projets/buildroot/output/host/lib/python3.7/py_compile.py", line 136, in compile
_optimize=optimize)
File "<frozen importlib._bootstrap_external>", line 763, in source_to_code
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "usr/lib/python3.7/site-packages/circus/tests/support.py", line 210
debug=debug, async=True, **kw)
^
SyntaxError: invalid syntax
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>

circus/tests: rename async argument of _create_circus() to use_async

---

circus/config.py
circus/util.py

signum is type 'str' when passed to `def to_signum(signum)`.  If you enter an integer for the stop_signal in a circus ini file, the value falls through to the regular expression matching, and will fail with a ValueError.  The patch will attempt to cast the 'str' to an 'int', if it fails it will then pass the value through to the regular expression.

allow stop_signal to be an integer in circus configuration file

---

circus/commands/util.py
circus/tests/test_watcher.py
circus/watcher.py
docs/source/for-devs/writing-hooks.rst
docs/source/for-ops/configuration.rst

Related to #1103 
I am not sure if I need to take care of the hook result ?

Added before_reap and after_reap hooks

---

circus/arbiter.py
circus/controller.py
circus/plugins/__init__.py
circus/plugins/command_reloader.py
circus/plugins/statsd.py
circus/plugins/watchdog.py
circus/stats/collector.py
circus/stats/streamer.py
circus/stream/papa_redirector.py
circus/stream/redirector.py
circus/tests/support.py
circus/tests/test_stats_collector.py
circus/watcher.py
setup.py
tox.ini

Fixes #1099 
Update the dependency requirement `pyzmq>=17` and update the code
to adapt to corresponding API changes.
~~@k4nar This is blocked by PR #1110 that I opened that first fixes the CI on Travis.
I hope this PR will breath back some life into circus. I intend to look into porting the
code to `tornado>5` in the near future, but this is more complicated. Any help or
directions there would be very welcome.~~

Update the `pyzmq` dependency

---

circus/config.py
circus/tests/config/issue1088.ini
circus/tests/test_config.py

Fixes #1088 
- change reading of graceful_timeout in config to float
- add separate test with graceful_timeout set as float

graceful_timeout watcher config option should be float

---

circus/circusd.py

- the pid file should be remove just before exiting
Fixes #1080

Do not delete pid file during restart

---

tox.ini

PyYAML dropped support of python 3.4 in version 5.3 and tests started to fail. I added version requirement in tox config to fix this.

Add PyYAML version requirement to py34 tox config

---

circus/arbiter.py
circus/tests/test_arbiter.py

- add conversion to lowercase when checking for existing watcher
- add test with two watchers foo and Foo, which should raise
Fixes #936

Do not allow adding watchers with the same lowercase names

---

circus/arbiter.py

This is just a touch up on #834 by @majek.
I removed all occurrences of `get_socket_config` and didn't change any other logic.
I have also tested the assumption that this change would speed up the reloading of the config. My method of test was the following:
- generate two fairly large configs (with at least 1000 sockets)
- make sure reloading happens more than once
- average out the time of execution using statistics module
All of the test files are [here](https://gist.github.com/biozz/7020a4d65f25245f45aab937f5482fb6).
On my machine the results were:
- with `get_socket_config`: ~0.23 sec
- without `get_socket_config`: ~0.18 sec
And on the other hand, the reloading of the smaller files (with 1-2 sockets) took almost the same time.
The change looks insignificant to me, but also "nice to …

Speedup reload of configs with large number of sockets

---

circus/tests/test_util.py
circus/util.py

This fixes #1127.
- add conversion to string and cutting to 2 decimal places
- add tests for edge cases with 1.99G and 2.00G

Fix mem_info readings to be more reliable

---

docs/source/changelog.rst
docs/source/contributing.rst

I added unreleased section to changelog after being inspired by [keepachangelog](https://keepachangelog.com/) project.
I have also added a small note to contributing guide with a reminder to add such entries.

Keep a changelog

---

circus/plugins/watchdog.py

Closes #1105.
The main change is adding `decode`, because it is sent over socket as bytes. I also fixed small typing error in the warning.
Unfortunately I couldn't figure out how to reproduce this bug in a test case. It would be great if I could get some help with that. On the other hand I can see that there is no exception (`TypeError`) when executing tests, so `decode` does not make it worse.

Add decoding of data when receiving watchdog message

---

circus/util.py
docs/source/changelog.rst
examples/example2.ini

Closes #1097.
The first implementation of time_format feature was done in #493, there was also a test, which checked that the feature works as expected.
But the test was designed in such a way that it used `FileStream` class and not the configuration file (like some other tests). Therefore the error described in #1097 wouldn't appear.
I changed `ConfigParser` to `RawConfigParser`, because it seems that interpolation feature, which is specific to `ConfigParser`, is not widely used and is not described in the documentation. So there is no reason to use `ConfigParser`.
I added `time_format` to `example2.ini` and did not add more tests, because if it not breaks and all of the other tests are working, then it should be OK.

Change ConfigParser to RawConfig parser to avoid interpolation errors

---

docs/source/tutorial/step-by-step.rst

Closes #1138.
`libzmq-dev` is now `libzmq3-dev` and we no longer support older version of python. The bad thing is that with new python versions `circus-web` is broken and you can't actually follow the guide.

Update tutorial with new versions of python and libzmq

---

circus/arbiter.py
circus/watcher.py

Issue #1131  when `quit` or `restart` is called with
`waiting` option, `arbiter.stop` is running to stop all the watchers,
processes, however, somehow `arbiter.stop()` is a coroutine which return
the Future is never get finished. Therefore, callback
`_dispatch_callback_future` of `controller` never get run.
After lots of debug attempts I find two workarounds.
1. When stop watchers and calling `Watcher().kill_process` do not wait
`tornado_sleep(0.1)` if process is still alive. This may cause some
unexpected side effects.
2. Just explicitly implement `__stop()` method of `Arbiter` class in
`stop()` and `restart()`. vvvery strange!!! Anyway, this doesn't
affect the code logic but get issue solved, so adapt to
workaround.
pinging @biozz @k4nar for inputs.

Fix #1131(workaround): explicitly code `__stop` in `stop` and `restart` methods of `Arbiter` class

---

.github/workflows/ci.yml
.gitignore
circus/tests/__init__.py
circus/tests/test_papa_stream.py
circus/tests/test_plugin_resource_watcher.py
circus/tests/test_stats_publisher.py
circus/tests/test_validate_option.py
setup.py
tox.ini

fix tests:
1. use a shared papa server for papa stream tests
2. test_stdout_stream and test_stderr_stream in TestValidateOption use a more specific assertion to avoid warn call from other modules.
3. test_resource_watcher_max_cpu set max_cpu to a very small value to get more deterministic results.
optimize:
1. TestStatsPublisher, remove duplicate code and manage zmq socket by hand, don't depend on the system to GC the socket, it's not reliable.

fix unit tests errors and add Python3.9 official support / Add Python3.9 and PyPy3.7 to CI flow

---

.github/workflows/ci.yml
setup.py
tox.ini

1. Add  PyPy38 to CI which requires Ubuntu upgrade to 20.04 to use latest binary dependencies that PyPy38 need;
2. Drop Python 3.5 and Python 3.6 from official support and CI.
NOTE: there seems to be some test case's result is not deterministic, I'll try to find out the root cause and fix it.

add pypy38 to ci

---

tox.ini

Remove circus-web dependency from tox.ini.
circus-web depends on a library called anyjson which cannot be installed with new version of setuptools, and anyjson is no longer maintained.
and circus-web is not used in the tests, so it should be removed.

Remove circus-web dependency from tox.ini

---

.github/workflows/ci.yml
circus/tests/test_papa_stream.py
circus/tests/test_util.py
circus/tests/venv/lib/python3.10/orig-prefix.txt
circus/tests/venv/lib/python3.10/site-packages/easy-install.pth
setup.py

Add Python 3.10 to the matrix of the CI workflow. All Python version numbers are properly wrapped in strings, otherwise they are interpreted as floats and `3.10` will become `3.1`.
The `setup.py` is updated to officially record support of Python 3.10 and the check for the minimum requirement is updated to actually check for Python 3.7, it was mistakenly still checking for Python 3.5.
Finally, the tests for the `papa` optional dependency are disabled because `papa` is not compatible with Python 3.10. It seems the project has been abandoned as the latest officially supported version is Python 3.4 and the last release was in early 2016.

Dependencies: Add support for Python 3.10

---

.github/workflows/cd.yml
.github/workflows/ci.yml

The `macos-10.15` runner has been deprecated and will be removed on December 22. The workflows have been getting cancelled on these runners.

DevOps: Update version of MacOS runners to `macos-12`

---

pyproject.toml

There were two invalid trove classifiers:
Operating System :: POSIX :: Windows
should be:
Operating System :: Microsoft :: Windows
And the license classifier had a trailing double quote. These mistakes were raised by `flit` when trying to publish the package. Valid
classifiers are provided by: https://pypi.org/classifiers/

DevOps: Fix the trove classifiers in the `pyproject.toml`

---

circus/tests/config/reload_statsd.ini
circus/tests/config/reuseport.ini
circus/tests/test_stdin_socket.py
circus/tests/test_umask.py
circus/util.py

* `pipes` module of standard library is replaced with `shlex`
* `pyzmq.utils.strtypes` was compatibility layer for Python 2 and 3.
The `u` method was to convert to unicode but this is no longer
applicable in Python 3 so can be removed.
* Address internal deprecation warnings of `statsd` not being set to
`True` in the config if a stats endpoint is defined.
The only warnings remaining is with respect to the misuse of event loops through `tornado`. However, this is more tricky to fix and would probably involve a bigger refactor, potentially even removing `tornado` altogether as now it is mostly a wrapper around `asyncio` of the standard library.

DevOps: Address deprecation warnings 

---

.github/workflows/ci.yml
tests/support.py
tests/venv/lib/python3.12/orig-prefix.txt
tests/venv/lib/python3.12/site-packages/easy-install.pth
tests/venv/lib/python3.13/orig-prefix.txt
tests/venv/lib/python3.13/site-packages/easy-install.pth

Needed to just update the tests, a class from unittest that was removed in py3.13 but was nowhere used in the code. There was nothing I had to change in the source code to let the test pass for py3.12 and py3.12. 
Also I ran aiida-core test suite with the almost latest version on master (I branched of PR #1218 a month ago or so) and almost all tests pass (see [test suite run](https://github.com/aiidateam/aiida-core/actions/runs/12928621322/job/36056307085?pr=6600)). Only 2 tests fail but I dont think they are related to circus.
This PR is related to issue #1215

Support tests for up to py3.13

---

circus/__init__.py
docs/source/changelog.rst

This PR is based on PR #1222
I think the same logic as in  Release v0.18.0 #1207 goes
> @biozz I bumped the minor version since we are removing support for `papa` but since we are still pre v1.0, we "technically" could just go with `0.17.3` instead. Would be fine for me as well.
_Originally posted by @sphuber in https://github.com/circus-tent/circus/issues/1207#issuecomment-1318792890_
So technically this could be a 0.18.1 release, but since in that PR a new major release was used I just imitated it.

Release 0.19.0
