docs/source/for-devs/adding-commands.rst
[When adding a new command to circus](https://github.com/sebschlicht/bachelor-thesis/wiki/HowTo:-Create-a-custom-circus-command) I ran into several issues:
1. missing import statements (Command, ArgumentError, MessageError)
2. NotImplementedError: message function not implemented
I browsed your code looking for an example and to get an idea of `message`'s purpose.
This pull requests adds the missing import statements and the `message` function together with a brief explanation to the code example.
Please check if I got the function's purpose.
=> Doc/Adding-commands: Import statements, message function

circus/commands/util.py
* close_child_stdout
* close_child_stderr
=> added worker options to ZMQ message API

circus/commands/decrproc.py, circus/commands/incrproc.py
@tarekziade fixed all comments in one commit.
=> Updated decrproc and incrproc. Corrected comments

debian/circus.init
=> Wait for process to exit before returning from do_stop

circus/tests/test_client.py
The test checks whether the hook is called from the client. This should help with #872
=> Fixes test_client to use gen_test.

circus/arbiter.py, circus/commands/restart.py, circus/commands/start.py, circus/commands/stop.py
=> Actions on multiple watchers

docs/source/tutorial/rationale.rst
Just some minor things I noticed will reading.
=> Minor doc fixes

circus/stream/file_stream.py, circus/tests/test_stream.py, circus/watcher.py
This is a fix for #912. Linked to #885.
@scottkmaxwell: As you worked with streams more than me, could you review this?
=> Re-open stream handlers when starting

circus/papa_process_proxy.py
=> Detect psutil that is too old for papa

.travis.yml
=> Use new Travis container based environment

circus/commands/util.py, circus/config.py, circus/process.py, circus/watcher.py, docs/source/for-ops/configuration.rst
This is just a rebase of #910 without the merge commit.
=> [Rebase of #910] New option "close_child_stdin" for watchers 

circus/papa_process_proxy.py
Fixes issues with args parsing with use_papa = True
=> Handle string args

circus/tests/test_sockets.py, docs/circus_ext.py, examples/addworkers.py, examples/apis.py, examples/byapi.py, examples/flask_app.py, examples/flask_redirect.py, examples/flask_serve.py, examples/hang.py, examples/simplesocket_client.py, examples/verbose_fly.py, examples/webclient/bread.py
Just deleted a couple leftover lines from #973 since it was already merged.
Also cleaned up some very minor pep8 issues while I'm at it.
=> Minor cleanup

circus/process.py, circus/tests/test_stdin_socket.py, circus/watcher.py, docs/source/for-ops/configuration.rst
=> stdin_socket

circus/pidfile.py, circus/tests/test_pidfile.py
This is just a rebase of #969 against the current master.
=> Rebase of #969

circus/stream/redirector.py
=> Rebase of #980

setup.py
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> setup.py: skip examples from installing as a package

setup.py
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> setup.py: drop iowait from requirements

circus/config.py, setup.py, tox.ini
=> Fix unicode error with Python 2 in get_config

circus/arbiter.py, circus/config.py
This was tested in a live environment.
=> bugfix: papa_endpoint ipc socket is ignored, tcp is created issue #1066

.travis.yml, setup.py, tox.ini
=> Lock tornado version to pre-5.0 and PyZMQ version to pre-17.0

circus/tests/test_config.py, circus/util.py, docs/source/changelog.rst
Fixes the issue mentioned in #1159
=> Fix custom syslog destination

circus/util.py
=> fix virtualenv loading with Python 3.10

circus/controller.py, circus/green/controller.py, circus/plugins/command_reloader.py, circus/plugins/statsd.py, circus/plugins/watchdog.py, circus/stats/collector.py, circus/tests/venv/lib/python3.9/orig-prefix.txt, circus/tests/venv/lib/python3.9/site-packages/easy-install.pth, circus/util.py
now tornado support run async function with PeriodicCallback [#2924](https://github.com/tornadoweb/tornado/pull/2924)
=> AsyncPeriodicCallback to replace PeriodicCallback

circus/tests/test_util.py, circus/util.py
This is a patch related to issue: https://github.com/circus-tent/circus/issues/1177
=> a patch to handle pypy venv site-packages directory

circus/arbiter.py, circus/tests/test_arbiter.py
Patch tornado ioloop handle callback exception, related to issue: https://github.com/circus-tent/circus/issues/1179
=> Patch tornado ioloop handle callback exception

circus/arbiter.py, circus/circusd.py, circus/watcher.py
log more information when bad things happened to help find out what caused the problem
=> log more information when bad things happened

circus/tests/support.py
We can't use close to release the port resource. The close function just decrease the reference count and the actual cleanup is performed by the OS.
In our test cases:
1. we create a socket and and 
2. bind it to a port selected by OS kernel
3. extract the port from the socket and then return it
4. close the socket
**5. we assume that the port resource is available**
We cannot ensure the fifth expectation is true, because the release of the port is not performed by the close function, it's released by the system when it sees the reference count to this socket is zero.
So, we must add some machanism to wait for the system releasing the port resource.
@k4nar
=> Add retry when arbiter start failed in tests

.github/workflows/cd.yml, .github/workflows/validate_release_tag.py
The `cd.yml` is a Github Actions workflow that triggers when a new tag is pushed to the source repository. It will check that the version specified in the `__version__` attribute matches that of the tag, and if the case will run the full test suite. If all tests pass, the package will be built using `flit` and pushed to PyPI. This will significantly simplify and automate the release process.
=> DevOps: Add continuous-deployment workflow

pyproject.toml
I think with PR #1221 we can add this now to the package metadata
=> Add into the package metadata that up to Python 3.13 is supported
